# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/hardware/network/broadcom-43xx.nix>
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/db038e69-6a89-44af-ac91-6e1f78423f60";
      fsType = "ext4";
    };


  fileSystems."/home" =
    { 
      #device = "/dev/disk/by-uuid/a5679a99-ddbe-4986-9955-8fb246ff0e71";
      #fsType = "btrfs";
      device = "/dev/disk/by-uuid/c00241c6-e32f-42c9-b284-9243e22736bb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A65-079D";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
